'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),Module=require('node:module');
const originalLoad=Module._load;Module._load=function(request,parent,isMain){if(request==='mime-types')return {lookup:file=>String(file).endsWith('.png')?'image/png':String(file).endsWith('.jpg')?'image/jpeg':'application/octet-stream'};return originalLoad.call(this,request,parent,isMain);};const {CloudQueue}=require('../src/main/cloud-queue');Module._load=originalLoad;
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'dtdc-cloud-test-')),patient={clinicId:'A',patientId:'p1',patientDir:path.join(root,'patient-A')};fs.mkdirSync(patient.patientDir);const file=path.join(patient.patientDir,'xray.png');fs.writeFileSync(file,Buffer.from('synthetic-only'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return {root,patient,file};}
const settled=async q=>{for(let i=0;i<100&&q.running;i++)await new Promise(r=>setTimeout(r,5));};
function googleFixture(){const saved=[];return {session:null,status:()=>({connected:true}),setSession(v){this.session=v;},beginUpload:async spec=>'https://upload.example/session',uploadChunk:async(_url,chunk,start,total)=>({done:true,next:total,file:{id:'drive-file-1',size:total}}),putMedia:async(spec,id)=>{saved.push({spec,id});return {driveFileId:id};},saved};}

test('upload queue persists without OAuth or Firebase tokens and writes Drive metadata after success',async t=>{const f=setup(t),g=googleFixture(),q=new CloudQueue({directory:f.root,google:g});t.after(()=>q.close());q.enqueue(f.file,f.patient,'xrays');q.setSession({uid:'u',clinicId:'A',role:'manager',projectId:'demo',token:'firebase-secret-token',enabled:true});await settled(q);assert.equal(q.rows.length,0);assert.equal(g.saved.length,1);assert.equal(g.saved[0].spec.patientId,'p1');assert.equal(g.saved[0].id,'drive-file-1');const persisted=fs.readFileSync(q.file,'utf8');assert(!persisted.includes('firebase-secret-token'));assert.equal(fs.readFileSync(f.file,'utf8'),'synthetic-only');});

test('failed resumable upload remains queued and retains local original',async t=>{const f=setup(t),g=googleFixture();g.uploadChunk=async()=>{throw Object.assign(new Error('google_http_503'),{code:'google_http_503',status:503});};const q=new CloudQueue({directory:f.root,google:g});t.after(()=>q.close());q.enqueue(f.file,f.patient,'xrays');q.setSession({uid:'u',clinicId:'A',role:'manager',projectId:'demo',token:'fixture',enabled:true});await settled(q);assert.equal(q.rows.length,1);assert.equal(q.rows[0].lastError,'google_http_503');assert.equal(fs.readFileSync(f.file,'utf8'),'synthetic-only');});

test('bulk archive migration only queues current clinic and uses manifest identity',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'dtdc-bulk-')),queueDir=path.join(root,'queue'),archiveRoot=path.join(root,'Dental Chain Patients');fs.mkdirSync(queueDir);fs.mkdirSync(archiveRoot);t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const [folder,clinic,patient] of [['a','A','p1'],['b','B','p2']]){const d=path.join(archiveRoot,folder);fs.mkdirSync(path.join(d,'Photos'),{recursive:true});fs.writeFileSync(path.join(d,'patient.json'),JSON.stringify({clinicId:clinic,patientId:patient}));fs.writeFileSync(path.join(d,'Photos','one.jpg'),'image');}const g=googleFixture();const q=new CloudQueue({directory:queueDir,google:g});t.after(()=>q.close());q.session={uid:'u',clinicId:'A',role:'manager',projectId:'demo',token:'x',enabled:true,at:Date.now()};q.running=true;const r=await q.enqueueAllArchives(archiveRoot);q.running=false;assert.equal(r.patients,1);assert.equal(r.otherClinic,1);assert(q.rows.every(x=>x.spec.clinicId==='A'&&x.spec.patientId==='p1'));});
