'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),mime=require('mime-types');
function inside(root,file){const relative=path.relative(root,file);return relative&&!relative.startsWith('..'+path.sep)&&relative!=='..'&&!path.isAbsolute(relative);}
function portable(root,file){return path.relative(root,file).split(path.sep).filter(Boolean).slice(0,16).map(part=>part.slice(0,120)).join('/').slice(0,900);}
function readPatientManifest(dir){
  const rows=[];for(const name of ['patient.json','_patient.json','.dtdc-patient.json']){const file=path.join(dir,name);if(!fs.existsSync(file))continue;try{const row=JSON.parse(fs.readFileSync(file,'utf8'));if(!row||typeof row!=='object'||Array.isArray(row))throw new Error('invalid');rows.push(row);}catch{throw new Error('invalid_patient_manifest');}}
  const identities=new Set(rows.filter(row=>row.clinicId&&(row.patientId||row.id)).map(row=>JSON.stringify([String(row.clinicId),String(row.patientId||row.id)])));if(identities.size>1)throw new Error('conflicting_patient_manifest');return rows.find(row=>row.clinicId&&(row.patientId||row.id))||rows[0]||null;
}
function categoryFor(relative,file){const value=String(relative||'').toLowerCase(),type=mime.lookup(file)||'';if(/treatmentplans|خطط العلاج/.test(value))return 'plans';if(/panorama|sensor|xray|radiograph|أشعة/.test(value))return 'xrays';return /^image\//.test(type)?'photos':'attachments';}
class CloudQueue{
  constructor({directory,onNotice=()=>{},google}){this.file=path.join(directory,'cloud-upload-queue.json');this.tempDir=path.join(directory,'cloud-upload-cache');this.notice=onNotice;this.google=google;this.session=null;this.generation=0;this.running=false;try{this.rows=JSON.parse(fs.readFileSync(this.file,'utf8'));if(!Array.isArray(this.rows))throw new Error('invalid_cloud_queue');}catch(e){if(e.code!=='ENOENT')throw e;this.rows=[];}this.timer=setInterval(()=>void this.flush(),30000);this.timer.unref?.();}
  persist(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.'+crypto.randomUUID()+'.tmp';fs.writeFileSync(tmp,JSON.stringify(this.rows),'utf8');fs.renameSync(tmp,this.file);}
  setSession(value){this.google?.setSession(value);if(!value||typeof value.token!=='string'||value.token.length>16000||!value.uid||!value.clinicId){this.session=null;this.generation++;return;}const next={...value,token:String(value.token),uid:String(value.uid),clinicId:String(value.clinicId),role:String(value.role||''),projectId:String(value.projectId||''),enabled:value.enabled===true,at:Date.now()};if(!this.session||JSON.stringify([this.session.uid,this.session.clinicId,this.session.role,this.session.enabled,this.session.projectId])!==JSON.stringify([next.uid,next.clinicId,next.role,next.enabled,next.projectId]))this.generation++;this.session=next;void this.flush();}
  makeSpec(file,patient,category='attachments',planId=''){const root=fs.realpathSync(patient.patientDir),target=fs.realpathSync(file);if(!inside(root,target)||!fs.statSync(target).isFile())throw new Error('cloud_file_outside_patient');const stat=fs.statSync(target),size=stat.size;if(!size||size>100*1024*1024){this.notice('ملف الأرشيف يتجاوز حد الرفع 100 ميغا؛ بقي محفوظاً محلياً.','warning');return null;}const sha256=crypto.createHash('sha256').update(fs.readFileSync(target)).digest('hex'),relativePath=portable(root,target);const spec={clinicId:String(patient.clinicId),patientId:String(patient.patientId),planId:String(planId||''),category,name:path.basename(file),relativePath,mimeType:mime.lookup(file)||'application/octet-stream',size,sha256};if(spec.mimeType==='application/json'||!/^[-\w.+]+\/[-\w.+]+$/i.test(spec.mimeType))spec.mimeType='application/octet-stream';return {root,target,spec};}
  enqueue(file,patient,category='attachments',planId=''){if(!patient?.clinicId||!patient.patientId||!patient.patientDir)return false;const made=this.makeSpec(file,patient,category,planId);if(!made)return false;const {root,target,spec}=made,key=crypto.createHash('sha256').update(JSON.stringify([spec.clinicId,spec.patientId,spec.planId,category,spec.sha256])).digest('hex');if(this.rows.some(r=>r.key===key))return true;this.rows.push({key,file:target,root,spec,queuedAt:Date.now(),offset:0,sessionUrl:''});this.persist();void this.flush();return true;}
  enqueueBytes(bytes,spec){const data=Buffer.from(bytes);if(!data.length||data.length>100*1024*1024)throw new Error('file_size');const sha256=spec.sha256||crypto.createHash('sha256').update(data).digest('hex');if(spec.sha256&&sha256!==crypto.createHash('sha256').update(data).digest('hex'))throw new Error('upload_hash_mismatch');fs.mkdirSync(this.tempDir,{recursive:true});const key=crypto.createHash('sha256').update(JSON.stringify([spec.clinicId,spec.patientId,spec.planId||'',spec.category||'attachments',sha256])).digest('hex');if(this.rows.some(r=>r.key===key))return {queued:false,existing:true,key};const target=path.join(this.tempDir,key+'.bin');fs.writeFileSync(target,data);this.rows.push({key,file:target,root:this.tempDir,temp:true,spec:{...spec,sha256,size:data.length,mimeType:spec.mimeType||'application/octet-stream',name:spec.name||'attachment'},queuedAt:Date.now(),offset:0,sessionUrl:''});this.persist();void this.flush();return {queued:true,key};}
  enqueueArchive(patient,knownPlanIds=[]){const root=fs.realpathSync(patient.patientDir);let files=0,queued=0,existing=0,oversized=0;const scan=dir=>{for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(entry.isSymbolicLink())continue;const target=path.join(dir,entry.name);if(entry.isDirectory()){if(!entry.name.endsWith('.tmp'))scan(target);continue;}if(!entry.isFile()||/\.tmp$/i.test(entry.name)||/^~\$/.test(entry.name))continue;files++;const relative=portable(root,target),parts=relative.split('/'),candidate=/^(AssistantSessions|09 - جلسات المساعد)$/i.test(parts[0])?parts[1]||'':'',planId=knownPlanIds.includes(candidate)?candidate:'',category=categoryFor(relative,target),before=this.rows.length,result=this.enqueue(target,patient,category,planId);if(result){if(this.rows.length>before)queued++;else existing++;}else if(fs.statSync(target).size>100*1024*1024)oversized++;}};scan(root);return {files,queued,existing,oversized};}
  async enqueueAllArchives(rootDir){const session=this.session;if(!session?.enabled)throw new Error('cloud_not_enabled');if(!['manager','super_owner'].includes(session.role))throw new Error('role_denied');if(Date.now()-session.at>90000)throw new Error('session_changed');const root=fs.realpathSync(rootDir),stats={patients:0,files:0,queued:0,existing:0,oversized:0,noIdentity:0,otherClinic:0,conflicts:0};let touched=0;for(const entry of fs.readdirSync(root,{withFileTypes:true})){if(!entry.isDirectory()||entry.isSymbolicLink())continue;const patientDir=path.join(root,entry.name);let manifest;try{manifest=readPatientManifest(patientDir);}catch{stats.conflicts++;continue;}const clinicId=String(manifest?.clinicId||''),patientId=String(manifest?.patientId||manifest?.id||'');if(!clinicId||!patientId){stats.noIdentity++;continue;}if(clinicId!==session.clinicId){stats.otherClinic++;continue;}const result=this.enqueueArchive({clinicId,patientId,patientDir},[]);stats.patients++;for(const key of ['files','queued','existing','oversized'])stats[key]+=result[key]||0;if((touched+=result.files)>=20){touched=0;await new Promise(resolve=>setImmediate(resolve));}}void this.flush();return stats;}
  summary(clinicId=''){const rows=this.rows.filter(r=>!clinicId||r.spec?.clinicId===clinicId);return {count:rows.length,bytes:rows.reduce((s,r)=>s+Number(r.spec?.size||0),0),rows:rows.map(r=>({name:r.spec?.name,status:r.lastError?'retry':'pending',lastError:r.lastError||'',offset:r.offset||0,size:r.spec?.size||0}))};}
  async flush(){const s=this.session,epoch=this.generation;if(this.running||!s?.enabled||Date.now()-s.at>90000||!this.google?.status().connected)return;this.running=true;const active=()=>this.generation===epoch&&this.session?.enabled&&Date.now()-this.session.at<90000;try{for(const row of [...this.rows].filter(r=>r.spec.clinicId===s.clinicId)){if(!active())break;try{if(!fs.existsSync(row.file)){this.rows=this.rows.filter(r=>r.key!==row.key);this.persist();continue;}if(!row.temp&&!inside(row.root,fs.realpathSync(row.file)))throw new Error('cloud_file_outside_patient');const stat=fs.statSync(row.file);if(stat.size!==row.spec.size){this.rows=this.rows.filter(r=>r.key!==row.key);this.persist();if(!row.temp)this.enqueue(row.file,{clinicId:row.spec.clinicId,patientId:row.spec.patientId,patientDir:row.root},row.spec.category,row.spec.planId);continue;}if(!row.sessionUrl){row.sessionUrl=await this.google.beginUpload(row.spec);row.offset=0;this.persist();}const fd=fs.openSync(row.file,'r');try{while((row.offset||0)<row.spec.size){if(!active())throw Object.assign(new Error('session_changed'),{code:'session_changed'});const start=row.offset||0,len=Math.min(4*1024*1024,row.spec.size-start),chunk=Buffer.allocUnsafe(len),read=fs.readSync(fd,chunk,0,len,start),result=await this.google.uploadChunk(row.sessionUrl,chunk.subarray(0,read),start,row.spec.size,row.spec.mimeType);row.offset=result.next;this.persist();if(result.done){await this.google.putMedia(row.spec,result.file.id,'uploaded');row.offset=row.spec.size;break;}}}finally{fs.closeSync(fd);}this.rows=this.rows.filter(r=>r.key!==row.key);this.persist();if(row.temp)try{fs.unlinkSync(row.file);}catch{}this.notice('تم حفظ نسخة من ملف الأرشيف على Google Drive.','success');}catch(e){if([404,410].includes(e.status)){row.sessionUrl='';row.offset=0;}row.lastError=e.code||e.message;row.attempts=(row.attempts||0)+1;this.persist();this.notice('رفع الأرشيف معلّق؛ النسخة المحلية محفوظة وسيُعاد المحاولة.','warning');if([401,403].includes(e.status)||!active())break;}}}finally{this.running=false;}}
  close(){clearInterval(this.timer);this.setSession(null);}
}
module.exports={CloudQueue,inside};
