"use strict";
const express=require("express"),http=require("http"),fs=require("fs"),crypto=require("crypto"),mime=require("mime-types");
let sharp=null;try{sharp=require("sharp")}catch{}
const {WebSocketServer,WebSocket}=require("ws");const {getLocalIPv4}=require("./discovery");
class ChairServer{
 constructor({port,maxWidth,maxHeight,onState,onNotice}){this.port=port;this.maxWidth=maxWidth;this.maxHeight=maxHeight;this.onState=onState||(()=>{});this.onNotice=onNotice||(()=>{});this.clients=new Set();this.media=new Map();this.pending=new Map();this.currentState=null;this.sessionId="";this.lastDisconnectReason=""}
 state(){const ip=getLocalIPv4()[0]||"127.0.0.1";return{clients:this.clients.size,ip,wsUrl:`ws://${ip}:${this.port}`,httpUrl:`http://${ip}:${this.port}`,sessionId:this.sessionId,lastDisconnectReason:this.lastDisconnectReason,pendingAcks:this.pending.size}}
 setSession(id){this.sessionId=String(id||"");this.pending.clear()}
 setCurrentState(v){this.currentState=v||null}
 async start(){const app=express();app.get('/health',(_q,r)=>r.json({ok:true,product:'DentalChairController',protocol:3,sessionId:this.sessionId}));app.get('/media/:id',async(q,r)=>{const e=this.media.get(q.params.id);if(!e||!fs.existsSync(e.path))return r.sendStatus(404);try{r.setHeader('Cache-Control','no-store');if(e.optimizeImage&&sharp){r.type('image/jpeg');sharp(e.path).rotate().resize({width:this.maxWidth,height:this.maxHeight,fit:'inside',withoutEnlargement:true}).jpeg({quality:91,mozjpeg:true}).pipe(r)}else{r.type(mime.lookup(e.path)||'application/octet-stream');fs.createReadStream(e.path).pipe(r)}}catch{r.sendStatus(500)}});this.server=http.createServer(app);this.wss=new WebSocketServer({server:this.server});this.wss.on('connection',s=>{s.isAlive=true;this.clients.add(s);s.on('pong',()=>s.isAlive=true);s.on('message',raw=>this.onMessage(s,raw));s.on('close',(code,reason)=>{this.lastDisconnectReason=`${code} ${String(reason||'')}`.trim();this.clients.delete(s);this.emit()});s.on('error',e=>{this.lastDisconnectReason=e.message||'socket error'});s.send(JSON.stringify({type:'hello',protocol:3,controllerVersion:'4.0.0',sessionId:this.sessionId}));if(this.currentState)setTimeout(()=>this.send(this.currentState,{important:true,warn:false}),180);this.emit()});this.timer=setInterval(()=>{for(const s of this.clients){if(!s.isAlive){s.terminate();this.clients.delete(s);continue}s.isAlive=false;try{s.ping()}catch{}}this.retryPending();this.emit()},5000);await new Promise((resolve,reject)=>{this.server.once('error',reject);this.server.listen(this.port,'0.0.0.0',resolve)});this.emit();this.onNotice(`خادم الشاشة يعمل على ${this.port}`,'success')}
 onMessage(_s,raw){try{const m=JSON.parse(String(raw));if(m.type==='ack'&&m.messageId)this.pending.delete(String(m.messageId));if(m.type==='display_ready'&&this.currentState)this.send(this.currentState,{important:true,warn:false})}catch{}}
 retryPending(){const now=Date.now();for(const [id,p] of this.pending){if(now-p.sentAt<2500)continue;if(p.tries>=3){this.pending.delete(id);this.onNotice(`لم تؤكد الشاشة استلام الأمر ${p.payload.type}`,'warning');continue}p.tries++;p.sentAt=now;this.broadcast(p.message)}}
 emit(){this.onState(this.state())}
 registerMedia(file,optimizeImage=false){const id=crypto.randomUUID();this.media.set(id,{path:file,optimizeImage,createdAt:Date.now()});if(this.media.size>120){const oldest=[...this.media.entries()].sort((a,b)=>a[1].createdAt-b[1].createdAt)[0];if(oldest)this.media.delete(oldest[0])}return`${this.state().httpUrl}/media/${id}`}
 broadcast(message){let count=0;for(const s of this.clients)if(s.readyState===WebSocket.OPEN){s.send(message);count++}return count}
 send(payload,options=true){const opts=typeof options==='boolean'?{warn:options}:options||{},messageId=opts.important?crypto.randomUUID():undefined,envelope={...payload,protocol:3,sessionId:payload.sessionId??this.sessionId,sentAt:Date.now(),messageId};const message=JSON.stringify(envelope),count=this.broadcast(message);if(opts.important&&messageId)this.pending.set(messageId,{payload:envelope,message,sentAt:Date.now(),tries:0});if(!['transform','plan_navigate','ping'].includes(payload.type))this.currentState=envelope;if(!count&&opts.warn!==false)this.onNotice(`شاشة الكرسي غير متصلة${this.lastDisconnectReason?`: ${this.lastDisconnectReason}`:''}`,'warning');return count}
}
module.exports={ChairServer};
