(()=>{
'use strict';
const $=id=>document.getElementById(id),uid=p=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
let appState={},plan=null,activeStage=0,panoramaPath='',drawing=false,currentPoints=[],selectedAnnotationId='',undoStack=[],redoStack=[],drag=null;
const DEFAULT_PALETTE=[
 {id:'urgent',name:'عاجل',color:'#ff5c68',opacity:.28,stroke:4},
 {id:'watch',name:'مراقبة',color:'#ffc24a',opacity:.25,stroke:4},
 {id:'stable',name:'بارد',color:'#67e9b7',opacity:.24,stroke:4},
 {id:'later',name:'مرحلة لاحقة',color:'#32d6ff',opacity:.23,stroke:4}
];
function patientReady(){return !!appState.patient?.selected}
function stage(){return plan.stages[activeStage]}
function snapshot(){undoStack.push(JSON.stringify(plan));if(undoStack.length>60)undoStack.shift();redoStack=[]}
function restore(raw){plan=JSON.parse(raw);activeStage=Math.min(activeStage,plan.stages.length-1);renderAll()}
function newPlan(){
 plan={id:'',title:'خطة العلاج المقترحة',currency:'USD',closingNote:'الخطة تقديرية وقد تتغير بعد الفحص السريري والاستجابة للعلاج.',panoramaPath:'',palette:structuredClone(DEFAULT_PALETTE),annotations:[],stages:[newStage()]};activeStage=0;panoramaPath='';undoStack=[];redoStack=[];renderAll();
}
function newStage(){return{stageId:uid('STAGE'),title:'مرحلة علاج جديدة',description:'',points:[],toothIds:[],annotationIds:[],priority:'متوسطة',prognosis:'جيد',status:'proposed',sessions:1,duration:'',cost:0,color:'#168fff',notes:'',imagePath:'',backgroundPath:'',order:Date.now()}}
function selectedPalette(){const id=$('annotationPalette')?.value||plan.palette[0]?.id;return plan.palette.find(x=>x.id===id)||plan.palette[0]}
function annotationById(id){return plan.annotations.find(x=>x.annotationId===id)}
function buildTabs(){
 const modal=$('planModal');if(!modal||modal.querySelector('.clinical-tabs'))return;
 const bar=document.createElement('div');bar.className='clinical-tabs';bar.innerHTML='<button data-tab="images" class="active">1 الصور والتحديد</button><button data-tab="teeth">2 الأسنان والعلامات</button><button data-tab="stages">3 مراحل العلاج</button><button data-tab="preview">4 العرض النهائي</button>';
 modal.querySelector('.workspace-head').after(bar);
 const panels=[...modal.querySelectorAll('.plan-panel')];panels[0].dataset.tab='images';panels[1].dataset.tab='stages';panels[2].dataset.tab='preview';
 const teeth=document.createElement('section');teeth.className='plan-panel teeth-link-panel';teeth.dataset.tab='teeth';teeth.innerHTML='<h3>الأسنان والعلامات المرتبطة</h3><p class="research-note">حدد علامة من الصورة ثم اختر الأسنان. أو اختر سنًا لمشاهدة العلامات والمراحل المرتبطة.</p><div id="toothLinkSummary" class="link-summary"></div>';
 modal.querySelector('.plan-layout').appendChild(teeth);
 bar.onclick=e=>{const b=e.target.closest('button');if(!b)return;bar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));modal.querySelectorAll('[data-tab]').forEach(x=>{if(x.classList.contains('clinical-tabs'))return;x.classList.toggle('tab-visible',x.dataset.tab===b.dataset.tab)});};
 panels[0].classList.add('tab-visible');
}
function enhanceTools(){
 const tools=$('annotationAdd')?.parentElement;if(!tools||$('annotationPalette'))return;
 tools.innerHTML=`<select id="annotationPalette"></select><button id="annotationStart">✎ رسم حدود حرة</button><button id="annotationClose">إغلاق الشكل</button><button id="annotationSelect">تحديد/تحريك</button><button id="annotationDelete">حذف المحدد</button><button id="annotationUndo">تراجع</button><button id="annotationRedo">إعادة</button><button id="annotationToggle">إخفاء العلامات</button><button id="annotationExport">تصدير مدمج</button><button id="paletteManage">إدارة الألوان</button>`;
 const box=document.createElement('div');box.id='annotationInspector';box.className='annotation-inspector';tools.after(box);
 $('annotationStart').onclick=()=>{drawing=true;currentPoints=[];selectedAnnotationId='';draw()};
 $('annotationClose').onclick=closePolygon;
 $('annotationSelect').onclick=()=>{drawing=false;currentPoints=[];draw()};
 $('annotationDelete').onclick=()=>{if(!selectedAnnotationId)return;snapshot();plan.annotations=plan.annotations.filter(x=>x.annotationId!==selectedAnnotationId);plan.stages.forEach(s=>s.annotationIds=s.annotationIds.filter(x=>x!==selectedAnnotationId));selectedAnnotationId='';renderAll()};
 $('annotationUndo').onclick=()=>{if(!undoStack.length)return;redoStack.push(JSON.stringify(plan));restore(undoStack.pop())};
 $('annotationRedo').onclick=()=>{if(!redoStack.length)return;undoStack.push(JSON.stringify(plan));restore(redoStack.pop())};
 $('annotationToggle').onclick=()=>{const c=$('planAnnotations');c.classList.toggle('annotations-hidden');$('annotationToggle').textContent=c.classList.contains('annotations-hidden')?'إظهار العلامات':'إخفاء العلامات'};
 $('annotationExport').onclick=exportComposite;
 $('paletteManage').onclick=managePalette;
}
function managePalette(){
 const action=prompt('اكتب: إضافة أو تعديل أو حذف','إضافة');if(!action)return;
 if(action.includes('إضافة')){const name=prompt('اسم التصنيف','جديد');const color=prompt('اللون HEX','#9d63ff');if(name&&/^#[0-9a-f]{6}$/i.test(color||'')){snapshot();plan.palette.push({id:uid('PAL'),name,color,opacity:.25,stroke:4});renderPalette()}}
 else{const p=selectedPalette();if(!p)return;if(action.includes('حذف')){if(plan.palette.length>1&&confirm(`حذف ${p.name}؟`)){snapshot();plan.palette=plan.palette.filter(x=>x.id!==p.id);renderPalette()}}else{const name=prompt('الاسم',p.name),color=prompt('اللون',p.color),opacity=Number(prompt('الشفافية 0-1',p.opacity)),stroke=Number(prompt('سماكة الحد',p.stroke));snapshot();Object.assign(p,{name:name||p.name,color:/^#[0-9a-f]{6}$/i.test(color||'')?color:p.color,opacity:Number.isFinite(opacity)?opacity:p.opacity,stroke:Number.isFinite(stroke)?stroke:p.stroke});renderPalette();draw()}}
}
function renderPalette(){const s=$('annotationPalette');if(!s)return;s.innerHTML=plan.palette.map(p=>`<option value="${p.id}">${p.name} · ${p.color}</option>`).join('')}
function closePolygon(){if(currentPoints.length<3)return alert('حدد ثلاث نقاط على الأقل');snapshot();const pal=selectedPalette(),a={annotationId:uid('ANN'),imageId:panoramaPath,color:pal.color,categoryId:pal.id,categoryName:pal.name,opacity:pal.opacity,strokeWidth:pal.stroke,points:currentPoints.map(p=>({...p})),toothIds:[...stage().toothIds],stageId:stage().stageId,note:''};plan.annotations.push(a);stage().annotationIds.push(a.annotationId);selectedAnnotationId=a.annotationId;currentPoints=[];drawing=false;renderAll()}
function pt(e){const r=$('planAnnotations').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
function hit(p){for(let i=plan.annotations.length-1;i>=0;i--){const a=plan.annotations[i];if(pointInPolygon(p,a.points))return a}return null}
function pointInPolygon(p,vs){let inside=false;for(let i=0,j=vs.length-1;i<vs.length;j=i++){const xi=vs[i].x,yi=vs[i].y,xj=vs[j].x,yj=vs[j].y;const intersect=((yi>p.y)!=(yj>p.y))&&(p.x<(xj-xi)*(p.y-yi)/(yj-yi+.0000001)+xi);if(intersect)inside=!inside}return inside}
function bindCanvas(){const c=$('planAnnotations');
 c.onpointerdown=e=>{if(!panoramaPath)return;const p=pt(e);if(drawing){currentPoints.push(p);draw();return}const a=hit(p);selectedAnnotationId=a?.annotationId||'';if(a){snapshot();drag={start:p,original:a.points.map(x=>({...x}))};c.setPointerCapture(e.pointerId)}renderAll()};
 c.onpointermove=e=>{if(!drag||!selectedAnnotationId)return;const p=pt(e),a=annotationById(selectedAnnotationId),dx=p.x-drag.start.x,dy=p.y-drag.start.y;a.points=drag.original.map(q=>({x:Math.max(0,Math.min(1,q.x+dx)),y:Math.max(0,Math.min(1,q.y+dy))}));draw()};
 c.onpointerup=()=>{drag=null};c.ondblclick=()=>drawing&&closePolygon();
}
function draw(){const c=$('planAnnotations'),img=$('planPanorama');if(!c||!img)return;const r=img.getBoundingClientRect(),w=Math.max(1,Math.round(r.width)),h=Math.max(1,Math.round(r.height));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;const x=c.getContext('2d');x.clearRect(0,0,w,h);if(c.classList.contains('annotations-hidden'))return;
 for(const a of plan.annotations){if(a.imageId&&panoramaPath&&a.imageId!==panoramaPath)continue;path(x,a.points,w,h);x.fillStyle=hexAlpha(a.color,a.opacity);x.fill();x.lineWidth=a.strokeWidth||4;x.strokeStyle=a.color;x.stroke();if(a.annotationId===selectedAnnotationId){x.save();x.fillStyle='#fff';for(const p of a.points){x.beginPath();x.arc(p.x*w,p.y*h,5,0,Math.PI*2);x.fill()}x.restore()}}
 if(currentPoints.length){path(x,currentPoints,w,h,false);x.strokeStyle=selectedPalette()?.color||'#fff';x.lineWidth=3;x.stroke();for(const p of currentPoints){x.beginPath();x.arc(p.x*w,p.y*h,4,0,Math.PI*2);x.fillStyle='#fff';x.fill()}}
}
function path(ctx,pts,w,h,close=true){ctx.beginPath();pts.forEach((p,i)=>(i?ctx.lineTo(p.x*w,p.y*h):ctx.moveTo(p.x*w,p.y*h)));if(close&&pts.length>2)ctx.closePath()}
function hexAlpha(hex,a){const n=parseInt(hex.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${a??.25})`}
function renderTeeth(){const chart=$('toothChart');if(!chart)return;const ids=['18','17','16','15','14','13','12','11','21','22','23','24','25','26','27','28','48','47','46','45','44','43','42','41','31','32','33','34','35','36','37','38'];chart.innerHTML=ids.map(id=>`<button data-tooth="${id}" class="${stage().toothIds.includes(id)?'selected':''}"><span class="tooth-shape">◉</span><b>${id}</b></button>`).join('');chart.onclick=e=>{const b=e.target.closest('[data-tooth]');if(!b)return;snapshot();const id=b.dataset.tooth,s=stage();s.toothIds=s.toothIds.includes(id)?s.toothIds.filter(x=>x!==id):[...s.toothIds,id];const a=annotationById(selectedAnnotationId);if(a)a.toothIds=[...s.toothIds];renderAll()}}
function renderLinks(){const box=$('toothLinkSummary');if(!box)return;box.innerHTML=plan.annotations.map(a=>`<article class="link-card ${a.annotationId===selectedAnnotationId?'selected':''}" data-ann="${a.annotationId}"><i style="background:${a.color}"></i><div><b>${a.categoryName||'علامة'}</b><small>الأسنان: ${(a.toothIds||[]).join('، ')||'غير مرتبطة'} · المرحلة: ${plan.stages.find(s=>s.stageId===a.stageId)?.title||'—'}</small></div></article>`).join('')||'<p>لا توجد علامات بعد.</p>';box.onclick=e=>{const a=e.target.closest('[data-ann]');if(a){selectedAnnotationId=a.dataset.ann;renderAll()}}}
function storeForm(){const s=stage();s.title=$('stageTitle').value.trim();s.description=$('stageDescription').value.trim();s.points=$('stagePoints').value.split('\n').map(x=>x.trim()).filter(Boolean);s.priority=$('stagePriority').value;s.prognosis=$('stagePrognosis').value;s.sessions=Number($('stageSessions').value||1);s.duration=$('stageDuration').value.trim();s.cost=Number($('stageCost').value||0);s.color=$('stageColor').value;s.notes=$('stageNotes').value.trim();s.imagePath=$('stageImagePath').value;s.backgroundPath=$('stageBackgroundPath').value;s.status=$('stageStatus')?.value||s.status}
function renderStageForm(){const s=stage();[['stageTitle',s.title],['stageDescription',s.description],['stagePoints',s.points.join('\n')],['stagePriority',s.priority],['stagePrognosis',s.prognosis],['stageSessions',s.sessions],['stageDuration',s.duration],['stageCost',s.cost],['stageColor',s.color],['stageNotes',s.notes],['stageImagePath',s.imagePath],['stageBackgroundPath',s.backgroundPath]].forEach(([id,v])=>{if($(id))$(id).value=v??''});if($('stageStatus'))$('stageStatus').value=s.status||'proposed'}
function renderStageTabs(){const box=$('stageTabs');box.innerHTML=plan.stages.map((s,i)=>`<button class="${i===activeStage?'active':''}" data-i="${i}">${i+1}. ${s.title||'مرحلة'}</button>`).join('');box.onclick=e=>{const b=e.target.closest('[data-i]');if(!b)return;storeForm();activeStage=Number(b.dataset.i);renderAll()}}
function renderStory(){const box=$('patientStory');box.innerHTML=plan.stages.map((s,i)=>`<article style="border-right-color:${s.color}"><b>${i+1}. ${s.title}</b><small>${s.toothIds.join('، ')||'—'} · ${s.status||'proposed'}</small><strong>${s.cost||0} ${plan.currency}</strong></article>`).join('');const cost=plan.stages.reduce((n,s)=>n+Number(s.cost||0),0),sessions=plan.stages.reduce((n,s)=>n+Number(s.sessions||0),0);$('planTotal').textContent=`${cost} ${plan.currency}`;$('planSessionsTotal').textContent=`${sessions} جلسة`}
function renderInspector(){const a=annotationById(selectedAnnotationId),box=$('annotationInspector');if(!box)return;box.innerHTML=a?`<b>${a.categoryName}</b><span>${a.annotationId}</span><label>ملاحظة<input id="annotationNote" value="${(a.note||'').replace(/"/g,'&quot;')}"></label>`:'<small>لم يتم تحديد علامة</small>';if($('annotationNote'))$('annotationNote').onchange=e=>{a.note=e.target.value}}
function renderAll(){buildTabs();enhanceTools();renderPalette();renderStageTabs();renderStageForm();renderTeeth();renderLinks();renderStory();renderInspector();$('planTitle').value=plan.title;$('planCurrency').value=plan.currency;$('planClosing').value=plan.closingNote;setTimeout(draw,30)}
async function refreshPanoramas(){const items=patientReady()?await chairAPI.listPanoramas():[];$('panoramaList').innerHTML='<option value="">اختر صورة المريض</option>'+items.map(x=>`<option value="${x.path}">${x.name}</option>`).join('');if(panoramaPath)$('panoramaList').value=panoramaPath}
function payload(){storeForm();plan.title=$('planTitle').value.trim();plan.currency=$('planCurrency').value;plan.closingNote=$('planClosing').value.trim();plan.panoramaPath=panoramaPath;plan.totalCost=plan.stages.reduce((n,s)=>n+Number(s.cost||0),0);plan.totalSessions=plan.stages.reduce((n,s)=>n+Number(s.sessions||0),0);return plan}
async function save(show){if(!patientReady())return alert('افتح ملف المريض من Dental Chain OS');if(!panoramaPath)return alert('اختر بانوراما');const saved=await chairAPI.savePlan(payload());plan={...saved};await refreshPlans();if(show)await chairAPI.showPlan(saved);alert('تم حفظ الخطة وطبقة العلامات')}
async function refreshPlans(){const items=patientReady()?await chairAPI.listPlans():[];$('savedPlans').innerHTML='<option value="">— اختر خطة —</option>'+items.map(x=>`<option value="${x.id}">${x.title} · ${x.stagesCount} مراحل</option>`).join('')}
async function load(){const id=$('savedPlans').value;if(!id)return;plan=await chairAPI.loadPlan(id);plan.palette=plan.palette?.length?plan.palette:structuredClone(DEFAULT_PALETTE);plan.annotations=plan.annotations||[];plan.stages=(plan.stages||[]).map(s=>({...newStage(),...s,stageId:s.stageId||uid('STAGE'),toothIds:s.toothIds||s.teeth||[],annotationIds:s.annotationIds||[]}));activeStage=0;panoramaPath=plan.panoramaPath||'';await refreshPanoramas();if(panoramaPath){$('planPanorama').src=`file://${panoramaPath.replace(/\\/g,'/')}`;$('panoramaEmpty').style.display='none'}renderAll()}
async function openStudio(){if(!patientReady())return alert('افتح ملف المريض أولًا');$('planModal').classList.add('open');$('planPatientLabel').textContent=`${appState.patient.fullName} · ملف ${appState.patient.fileNo||'—'}`;await refreshPanoramas();await refreshPlans();renderAll()}
async function exportComposite(){const img=$('planPanorama'),c=$('planAnnotations');if(!img.src)return;const out=document.createElement('canvas');out.width=img.naturalWidth;out.height=img.naturalHeight;const x=out.getContext('2d');x.drawImage(img,0,0);for(const a of plan.annotations){path(x,a.points,out.width,out.height);x.fillStyle=hexAlpha(a.color,a.opacity);x.fill();x.lineWidth=a.strokeWidth||4;x.strokeStyle=a.color;x.stroke()}const file=await chairAPI.exportComposite(out.toDataURL('image/png'),`annotated-${Date.now()}.png`);alert(`تم التصدير:\n${file}`)}
function insertStatus(){if($('stageStatus'))return;const label=document.createElement('label');label.innerHTML='حالة المرحلة<select id="stageStatus"><option value="proposed">مقترحة</option><option value="approved">معتمدة</option><option value="in_progress">قيد التنفيذ</option><option value="completed">مكتملة</option></select>';$('stagePriority').closest('.form-grid').appendChild(label)}
window.addEventListener('DOMContentLoaded',()=>{insertStatus();buildTabs();enhanceTools();bindCanvas();newPlan();$('openPlanBuilder').onclick=openStudio;$('closePlan').onclick=()=>$('planModal').classList.remove('open');$('newPlan').onclick=()=>confirm('بدء خطة جديدة؟')&&newPlan();$('addStage').onclick=()=>{snapshot();storeForm();plan.stages.push(newStage());activeStage=plan.stages.length-1;renderAll()};$('deleteStage').onclick=()=>{if(plan.stages.length===1)return alert('يجب إبقاء مرحلة واحدة');snapshot();plan.stages.splice(activeStage,1);activeStage=Math.max(0,activeStage-1);renderAll()};$('panoramaList').onchange=e=>{panoramaPath=e.target.value;plan.panoramaPath=panoramaPath;if(panoramaPath){$('planPanorama').src=`file://${panoramaPath.replace(/\\/g,'/')}`;$('panoramaEmpty').style.display='none'}else $('panoramaEmpty').style.display='grid';setTimeout(draw,100)};$('importPanorama').onclick=async()=>{const x=await chairAPI.importPanorama();if(x){await refreshPanoramas();$('panoramaList').value=x.path;$('panoramaList').dispatchEvent(new Event('change'))}};$('savePlan').onclick=()=>save(false);$('presentPlan').onclick=()=>save(true);$('loadPlan').onclick=load;$('showSelectedPanorama').onclick=()=>panoramaPath?chairAPI.showPanorama(panoramaPath):alert('اختر صورة');$('openPatientFolder').onclick=()=>chairAPI.openPatientFolder();$('chooseStageImage').onclick=async()=>{const x=await chairAPI.choosePlanImage('image');if(x){$('stageImagePath').value=x;storeForm()}};$('chooseStageBackground').onclick=async()=>{const x=await chairAPI.choosePlanImage('background');if(x){$('stageBackgroundPath').value=x;storeForm()}};['planTitle','planCurrency','planClosing','stageTitle','stageDescription','stagePoints','stagePriority','stagePrognosis','stageSessions','stageDuration','stageCost','stageColor','stageNotes','stageStatus'].forEach(id=>$(id)?.addEventListener('change',()=>{storeForm();renderStory()}));window.addEventListener('resize',draw)});
chairAPI.onState(s=>{const old=appState.patient?.patientId;appState=s||{};if(old&&old!==appState.patient?.patientId){newPlan()}if($('planModal')?.classList.contains('open')&&patientReady())$('planPatientLabel').textContent=`${appState.patient.fullName} · ملف ${appState.patient.fileNo||'—'}`});
})();
